---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cabaebgf/loganate/uma-web
    - /bin/cp -R * $DEPLOYPATH || exit 1
    - /bin/cp .env.example $DEPLOYPATH/.env || exit 1
    - /bin/cp .htaccess $DEPLOYPATH/public/ || exit 1
    - export REPOPATH=/home/cabaebgf/repositories/loganate
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev || exit 1
    - php artisan key:generate || exit 1
    - php artisan config:cache || exit 1
    - php artisan route:cache || exit 1
    - php artisan view:cache || exit 1
    - php artisan storage:link || exit 1
    - chmod -R 755 storage bootstrap/cache || exit 1